openapi: 3.0.3
info:
  title: Integra API - OpenAPI 3.0
  description: |-
    This is ....
  termsOfService: http://swagger.io/terms/
  contact:
    email: frantisek.hylmar@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0.11'

paths:
  /api/v1/report:
    post:
      summary: Uploads content
      operationId: parseReport
      tags:
        - report
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: return successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportInfo'
                

  /api/v1/report/{reportId}:
    get:
      summary: Reads single report
      operationId: readReport
      tags:
        - report
      parameters:
        - name: reportId
          in: path
          required: true
          description: The id of the report to retrieve
          schema:
            type: string
      responses:
        '200':
          description: return successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'


  /api/v1/report/{reportId}/spans/{startIndex}/{endIndex}:
    get:
      summary: Reads spans within given range
      operationId: readReportRange
      tags:
        - report
      parameters:
        - name: reportId
          in: path
          required: true
          description: The id of the report to retrieve
          schema:
            type: string
        - name: startIndex
          in: path
          required: true
          description: The start index
          schema:
            type: string
        - name: endIndex
          in: path
          required: true
          description: The end index
          schema:
            type: string        
      responses:
        '200':
          description: return successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'


  /api/v1/report/{reportId}/span/{spanId}:
    get:
      summary: Reads report span
      operationId: readSpan
      tags:
        - report
      parameters:
        - name: reportId
          in: path
          required: true
          description: The id of the report to retrieve
          schema:
            type: string
        - name: spanId
          in: path
          required: true
          description: The id of the span to retrieve
          schema:
            type: string
      responses:
        '200':
          description: return successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpanDetail'


components:
  schemas:

    ReportInfo:
      type: object
      required:
        - id
        - rootSpanCount
      properties:
        id:
          type: string
        rootSpanCount:
          type: integer

    Report:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        spans:
          type: array
          items:
            $ref: '#/components/schemas/Span'
    
    Severity:
      type: string
      enum:
        - info
        - error

    Span:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        spanId:
          type: string
        traceId:
          type: string
        serviceName:
          type: string
        httpStatus:
          type: string
        httpMethod:
          type: string
        label:
          type: string
        timestamp:
          type: string
          format: date-time
        severity:
          $ref: '#/components/schemas/Severity'
        childSpans:
          type: array
          items:
            $ref: '#/components/schemas/Span'

    SpanDetail:
      allOf:
        - $ref: '#/components/schemas/Span'
        - type: object
          properties:
            request:
              type: string
            response:
              type: string
