/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Integra API - OpenAPI 3.0
 * This is ....
 * OpenAPI spec version: 1.0.11
 */

export type Severity = typeof Severity[keyof typeof Severity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Severity = {
  info: 'info',
  error: 'error',
} as const;
