/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Integra API - OpenAPI 3.0
 * This is ....
 * OpenAPI spec version: 1.0.11
 */
import type { Severity } from './severity';

export interface Span {
  id: string;
  spanId?: string;
  traceId?: string;
  serviceName?: string;
  httpStatus?: string;
  httpMethod?: string;
  label?: string;
  timestamp?: string;
  severity?: Severity;
  childSpans?: Span[];
}
