/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * Integra API - OpenAPI 3.0
 * This is ....
 * OpenAPI spec version: 1.0.11
 */
import type { ErrorResponseErrors } from './errorResponseErrors';

export interface ErrorResponse {
  code?: string;
  message?: string;
  description?: string;
  errors?: ErrorResponseErrors;
}
